### ISSUE TITLE
Event Gather is failing

### ISSUE THREAD

**Issue by whargrove** [OpenMontana/montana-legislature-council-data-project#37]
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/cdp_backend/bin/run_cdp_event_gather.py", line 88, in main
    flow = pipeline.create_event_gather_flow(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/cdp_backend/pipeline/event_gather_pipeline.py", line 118, in create_event_gather_flow
    events = get_events_func(
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/cdp_montana_legislature_backend/scraper.py", line 183, in get_events
    ].split(".", 1)[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

https://github.com/OpenMontana/montana-legislature-council-data-project/actions/runs/3851922251

**Comment by whargrove** [comment]
Fixed by 2291ba283e5ae212cdab912049bce2fd901504c7
